name: mcc-ai-construction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - pip
  - ifcopenshell=0.8.4
  - pip:
    - fastapi==0.109.0
    - uvicorn==0.27.0
    - python-multipart==0.0.6
    - ultralytics==8.4.6
    - opencv-python-headless==4.10.0.84
    - paddlepaddle==3.3.0
    - paddleocr==2.7.0.3
    - git+https://github.com/huggingface/transformers.git
    - accelerate==1.12.0
    - qwen-vl-utils==0.0.8
    - torch==2.9.1
    - torchvision==0.24.1
    - onnx==1.20.1
    - onnxruntime-gpu==1.23.2
    - onnxslim==0.1.82
    - numpy==1.26.4
    - requests==2.31.0
    - pillow==10.4.0
    - lark==1.1.9
    - roboflow==1.2.12
    - PyMuPDF==1.20.2
